---
- name: Install Docker
  gather_facts: No
  hosts: web
  become: yes
 
  tasks:
    - name: Disable SELinux
      command: setenforce 0

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
 
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
 
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: pls work
      command: dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm -y

    - name: make sure dnf-plugins.core installed
      dnf:
        name: dnf-plugins-core
        state: present
 
    - name: Add docker repo
      command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

    - name: dnf list docker-ce
      command: dnf list docker-ce

    - name: Install docker
      command: dnf install docker-ce -y

    - name: Make sure a service is running
      systemd:
        state: started
        name: docker

    - name: enable service docker and ensure it is not masked
      systemd:
        name: docker
        enabled: yes
        masked: no
